server.port=9090
spring.jackson.default-property-inclusion=always
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:stats;MODE=PostgreSQL;DB_CLOSE_DELAY=-1}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.sql.init.mode=never
