server:
  port: 0

grpc:
  server:
    port: 0

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:55434/ewm_analyzer}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  flyway:
    enabled: true
    locations: classpath:db/analyzer-migration
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  sql:
    init:
      mode: never
  kafka:
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 50
    listener:
      ack-mode: record
      concurrency: 1

stats:
  recommendations:
    history-size: 10
    neighbors-size: 5
