server:
  port: 0

grpc:
  server:
    port: 0

spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: ru.practicum.ewm.stats.serialization.AvroSerializer
      acks: all
      properties:
        enable.idempotence: true
        max.block.ms: 3000
        request.timeout.ms: 3000
        delivery.timeout.ms: 10000
