server:
  port: 0
  forward-headers-strategy: native

spring:
  application:
    name: event-service
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 1000
            readTimeout: 2000
    loadbalancer:
      cache:
        enabled: false
  jackson:
    default-property-inclusion: always
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:events;MODE=PostgreSQL;DB_CLOSE_DELAY=-1}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  flyway:
    locations: classpath:db/event-migration
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  sql:
    init:
      mode: never

ewm:
  events:
    min-start-delay-hours: 2
  display:
    retry:
      max-attempts: 2
      backoff-ms: 100
    circuit-breaker:
      sliding-window-size: 10
      minimum-number-of-calls: 2
      failure-rate-threshold: 50
      wait-duration-in-open-state-ms: 5000
      permitted-number-of-calls-in-half-open-state: 1

stats:
  service-id: stats-server
  discovery:
    max-attempts: 2
    backoff-ms: 100
  http:
    connect-timeout-ms: 1000
    read-timeout-ms: 2000
  circuit-breaker:
    sliding-window-size: 10
    minimum-number-of-calls: 1
    failure-rate-threshold: 50
    wait-duration-in-open-state-ms: 5000
    permitted-number-of-calls-in-half-open-state: 1
