server:
  port: 8080

spring:
  cloud:
    loadbalancer:
      cache:
        enabled: true
    gateway:
      x-forwarded:
        for-append: false
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/users/*/events/*/comments,/users/*/events/*/comments/**
        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests,/users/*/requests/**,/users/*/events/*/requests,/users/*/events/*/requests/**
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/admin/**,/users/**,/events/**,/categories/**,/compilations/**
