CREATE TABLE requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created TIMESTAMP NOT NULL,
    CONSTRAINT uq_requests_requester_event UNIQUE (requester_id, event_id),
    CONSTRAINT ck_requests_status CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED'))
);

CREATE INDEX idx_requests_requester ON requests(requester_id);
CREATE INDEX idx_requests_event_status ON requests(event_id, status);

CREATE TABLE request_user_guard (
    user_id BIGINT PRIMARY KEY,
    deleting BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE request_event_guard (
    event_id BIGINT PRIMARY KEY,
    deleting BOOLEAN NOT NULL DEFAULT false
);
