CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(2000) NOT NULL,
    author_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_on TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX idx_comments_event_created ON comments(event_id, created_on, id);
CREATE INDEX idx_comments_event_author_created ON comments(event_id, author_id, created_on, id);
CREATE INDEX idx_comments_author_id ON comments(author_id);

CREATE TABLE comment_user_guard (
    user_id BIGINT PRIMARY KEY,
    deleting BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE comment_event_guard (
    event_id BIGINT PRIMARY KEY,
    deleting BOOLEAN NOT NULL DEFAULT false
);
